version: '3'

services:
   backend:
        build:
           context: ./rest-api
           dockerfile: Dockerfile
        ports:
           - "80:8888"
        depends_on:
           - db-mysql
   db-mysql:
        image: mysql:5.6
        restart: always
        ports:
           - "3306:3306"
        environment:
           MYSQL_ROOT_PASSWORD: "dockerroot"
           MYSQL_DATABASE: "cloud_schema"
           MYSQL_USER: "root"
           MYSQL_PASSWORD: "root"
   